---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "kafka-config"
  namespace: "default"
  labels:
    app: "kafka"
data:
  KAFKA_CREATE_TOPICS: "test-topic:1:1"
  KAFKA_ZOOKEEPER_CONNECT: "35.225.85.208:2181"
  KAFKA_ADVERTISED_HOST_NAME: $SERVICE_EXTERNAL_IP
  KAFKA_ADVERTISED_PORT: 9092
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "kafka"
  namespace: "default"
  labels:
    app: "kafka"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "kafka"
  template:
    metadata:
      labels:
        app: "kafka"
    spec:
      containers:
      - name: "kafka"
        image: "wurstmeister/kafka"
        command:
        - "start-kafka.sh"
        env:
        - name: "KAFKA_CREATE_TOPICS"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_CREATE_TOPICS"
              name: "kafka-config"
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_ZOOKEEPER_CONNECT"
              name: "kafka-config"
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_ADVERTISED_HOST_NAME"
              name: "kafka-config"
        - name: "KAFKA_ADVERTISED_PORT"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_ADVERTISED_PORT"
              name: "kafka-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "kafka-hpa"
  namespace: "default"
  labels:
    app: "kafka"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "kafka"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
