---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "python-service"
  namespace: "default"
  labels:
    app: "python"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "python"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "python-config"
  namespace: "default"
  labels:
    app: "python"
data:
  HOST_KAFKA: "35.238.211.44"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "python"
  namespace: "default"
  labels:
    app: "python"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "python"
  template:
    metadata:
      labels:
        app: "python"
    spec:
      containers:
      - name: "python-kafka"
        image: "davisantana/python-kafka:0.2"
        env:
        - name: "HOST_KAFKA"
          valueFrom:
            configMapKeyRef:
              key: "HOST_KAFKA"
              name: "python-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "python-hpa"
  namespace: "default"
  labels:
    app: "python"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "python"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
