---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "zookeeper-service"
  namespace: "default"
  labels:
    app: "zookeeper"
spec:
  ports:
  - protocol: "TCP"
    port: 2181
    targetPort: 2181
  selector:
    app: "zookeeper"
  type: "LoadBalancer"
  loadBalancerIP: ""
